blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include,url
from . import views
app_name='blog'
urlpatterns=[
    url(r'^$',views.Indexview.as_view(),name='index'),
    url(r"^post/(?P<pk>[0-9]+)/$",views.Postdetailview.as_view(),name='detail'),
    # url(r"^post/(?P<pk>[0-9]+)/$",views.detail,name='detail'),
    url(r"^getPostdate/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$",views.Postdateview.as_view(),name='getPostdate'),
    url(r"^getCategory/(?P<pk>[0-9]+)/$",views.Categoryviews.as_view(),name='getCategory'),
    url(r"^getTag/(?P<pk>[0-9]+)/$",views.Tagviews.as_view(),name='getTag'),
    # url(r"^search/$",views.Seachviews.as_view,name="search"),
    #url(r'^search/$', views.search, name='search'),
]

comments/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include,url
from . import views
app_name='comments'
urlpatterns=[
    url(r'^comment/post/(?P<pk>[0-9]+)/$',views.comments,name='comments'),


]

web_0127/urls.py
# from django.contrib import admin
# from django.urls import path


from django.conf.urls import url, include
from django.contrib import admin
from blog.feed import AllPostsRssFeed
# from django.urls import path
urlpatterns = [
    url('^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

# 数据库
@python_2_unicode_compatible
class Category(models.Model):
    """
    #文章分类表
    """
    name=models.CharField(max_length=100)
    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Tag(models.Model):
    """
    文章标签表
    """
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Post(models.Model):
    """
    #文章表
    """
    #文章标题
    title=models.CharField(max_length=100)
    #文章分类
    #文章->分类一对多,不可以为空
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    #文章标签
    #文章<->标签多对多，可以不填写
    tags=models.ManyToManyField(Tag,blank=True)
    # 文章摘要
    summary=models.TextField(max_length=200,blank=True)
    #文章内容
    body=models.TextField()
    #文章创建时间
    create_time=models.DateTimeField()
    #文章最后修改时间
    finish_time=models.DateTimeField()
    #文章作者
    author=models.CharField(User,max_length=100)
    #文章点击量
    clicks=models.PositiveIntegerField(blank=True)
    def __str__(self):
        """
        #返回一个字符串
        :return:
        """
        return self.title
    def pagesclicks(self):
        """
        将文章的点击量+1，更新views字段
        :return:
        """
        self.clicks+=1
        self.save(update_fields=['clicks'])
#為了能夠在文章中随处可以进入到另一个url中，需要有一个可以重定像的url
#在这里使用url的反向解析，反过来找到url
    def get_absolute_url(self):
        """
        #reverse(viewname[, urlconf=None, args=None, kwargs=None, current_app=None])[source]¶
        #viewname可以是包含视图对象，URL pattern name或可调用视图对象的Python路径的字符串。
        :return:
        """
        return reverse('blog:detail',kwargs={'pk':self.pk})

    class Meta(object):
        ordering=['-create_time','title']

blog/views.py
import markdown
from django.shortcuts import render,get_object_or_404
from comments.forms import CommentForm
from .models import Post,Category,Tag
from django.views.generic import ListView,DetailView
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.db.models import Q

#文章列表页
# def index(request):
#     post_list=Post.objects.all()
#     return render(request,'blog/index.html',context={'post_list':post_list})
class Indexview(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by =2


    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        print(type(pagination_data))
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        right = page_range[page_number:page_number + 2]
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        if right:
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        if left:
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        data = {
                'left': left,
                'right': right,
                'left_has_more': left_has_more,
                'right_has_more': right_has_more,
                'first': first,
                'last': last,
            }

        return data
#详情页
def detail(request ,pk):
    post=get_object_or_404(Post,pk=pk)
    #文章阅读量+1
    post.pagesclicks()
    #引入markdown模块
    # post.body=markdown.Markdown(post.body,
    #                             extensions=[
    #                             'fenced_code',
    #                             'codehilite(css_class=highlight)',
    #                             'markdown.extensions.tables',
    #                             'toc',
    #                             'sane_lists',
    #                             ])
    post.body=mistune.markdown(post.body)
    form=CommentForm()
    comment_list=post.comments_set.all()
    comment_num=post.comments_set.count()
    context={
        'post':post,
        'form':form,
        'comment_list':comment_list,
        'comment_num':comment_num,
    }
    return render(request,'blog/detail.html',context=context)
#时间归档
# def getPostdate(request,year,month):
#     post_list=Post.objects.filter(create_time__year=year,
#                                   create_time__month=month)
#     return render(request,'blog/index.html',context={'post_list':post_list})
class Postdetailview(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        #阅读量+1
        #获得self.object 其值未Post的实例
        response=super().get(request,*args,**kwargs)
        self.object.pagesclicks()
        return response

    def get_object(self, queryset=None):
        post = super().get_object(queryset=None)
        md= markdown.Markdown(
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                          'markdown.extensions.tables',
                                          TocExtension(slugify=slugify),
                                      ])
        post.body=md.convert(post.body)
        post.toc=md.toc
        return post
    def get_context_data(self, **kwargs):
        context=super().get_context_data()
        form = CommentForm()
        comment_list = self.object.comments_set.all()
        comment_num = self.object.comments_set.count()
        context.update( {
            'post': self.object,
            'form': form,
            'comment_list': comment_list,
            'comment_num': comment_num,
        })
        return context

class Postdateview(Indexview):
    def get_queryset(self):
        """
        获取全部数据的函数
        官方解释：返回用来获取本视图显示对象的queryset。默认的，如果设置了queryset属性，
        get_queryset()返回它的值，否则该方法构造一个QuerySet通过调用model属性的默认管理器的all()方法。（我看不懂...）
        :return:
        """
        year=self.kwargs.get('year')
        month=self.kwargs.get('month')
        return super(Postdateview,self).get_queryset().filter(create_time__year=year,create_time__month=month)
        # post_list = Post.objects.filter(create_time__year=year,create_time__month=month)
#分类
# def getCategory(request,pk):
#     category=get_object_or_404(Category,pk=pk)
#     post_list=Post.objects.filter(category=category).order_by('-create_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})
class Categoryviews(Indexview):
    def get_queryset(self):
        pk=self.kwargs.get('pk')
        category = get_object_or_404(Category, pk=pk)
        return super().get_queryset().filter(category=category).order_by('-create_time')
# #标签云
# Create your views here.
class Tagviews(Indexview):
    def get_queryset(self):
        pk=self.kwargs.get('pk')
        tag = get_object_or_404(Tag, pk=pk)
        return super().get_queryset().filter(tags=tag)

# class Seachviews(Indexview):
#     def get_queryset(self):
#         q=self.kwargs.get('q')
#         if not q:
#             return super().get_queryset()
#         return super().get_queryset().filter(Q(title__icontains=q) | Q(body__icontains=q))
def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = "请输入关键词"
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg':error_msg ,'post_list': post_list})
# }

web_0127/templates/blog/detail.html
{% extends 'base.html' %}
{%load blog_tags%}
{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                {% get_Category as category_list %}
                    <span class="post-category"><a href="{% url 'blog:getCategory' post.category.pk %}">{{ post.category }} </a></span>
                <span class="post-date"><a href="#">
                    <time class="entry-date" datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ comment_num }}</a></span>
                <span class="views-count"><a href="#">{{ post.clicks }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:comments' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
{#                    <input type="text" name="formname" />#}
                </div>
{#                <div class="col-md-4">#}
{#                    <label for="{{ form.email.id_for_label }}">邮箱：</label>#}
{#                    {{ form.email }}#}
{#                    {{ form.email.errors }}#}
{##}
{#                </div>#}
                <div class="col-md-12">
                    <label for="{{ form.content.id_for_label }}">评论：</label>
                    {{ form.content }}
                    {{ form.content.errors }}
{#                    <input type="submit" value="Submit" />#}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h4>评论列表，共 <span>{{ comment_num }}</span> 条评论</h4>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date"
                              datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.content }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}

{% block toc %}
    <div class="directory">
        <h3 class="directory-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}

web_0127/templates/blog/index.html
{% extends 'base.html' %}
{%load blog_tags%}
{% block main %}
    {% if error_msg %}
    <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category">
                        {% get_Category as category_list %}
                            <a href="{% url 'blog:getCategory' post.category.pk %}">{{ post.category }}</a></span>
                    <span class="post-date">
                    <time class="entry-date" datetime="{{ post.create_time }}">{{ post.create_time }}</time></span>
{#                        <time class="entry-date" datetime="{{ date.year }}">{{ date.month }}</time></a></span>#}
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="post-clicks" >{{ post.clicks }}阅读 </span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p> {{ post.body | truncatechars:54 }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}




{% if is_paginated %}
<div class="pagination">
  {% if first %}
    <a href="?page=1">1</a>
  {% endif %}
  {% if left %}
    {% if left_has_more %}
        <span class="span" > ...</span>
    {% endif %}
    {% for i in left %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
  {% endif %}
  <a class="current-page" href="?page={{ page_obj.number }}" >{{ page_obj.number }}</a>
  {% if right %}
    {% for i in right %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% if right_has_more %}
        <span>...</span>
    {% endif %}
  {% endif %}
  {% if last %}
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
  {% endif %}
</div>
{% endif %}
{% endblock main %}